wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686335023.654413
    t:
      1:
      - 1
      - 33
      - 55
      - 86
      - 91
      - 95
      3:
      - 13
      - 15
      - 23
      4: 3.10.8
      5: 0.15.4
      8:
      - 5
